import {
  BadgeCheck,
  BarChart3,
  Building2,
  CircleHelp,
  CreditCard,
  Image as ImageIcon,
  Images,
  LayoutGrid,
  Mail,
  MapPin,
  Megaphone,
  MessageSquare,
  Minus,
  MousePointerClick,
  MoveVertical,
  Quote,
  Sparkles,
  Star,
  Type,
  Users,
  Video as VideoIcon,
} from 'lucide-react';
import { uid } from '../utils/helpers';
import { Banner, Footer, Header, RichText, Spacer } from './layout';
import {
  Faq,
  Features,
  Hero,
  ImageText,
  Newsletter,
  Testimonials,
} from './content';
import {
  CallToAction,
  ContactForm,
  Divider,
  Gallery,
  LogoCloud,
  MapEmbed,
  Pricing,
  Stats,
  Team,
  Video,
} from './extra';
import { FeaturedProduct, ProductGrid } from './commerce';
import {
  CTA_TONES,
  DIVIDER_STYLES,
  GRID_STYLES,
  IMAGE_SHAPES,
  IMAGE_SIZES,
  MAP_HEIGHTS,
  WIRE_SHAPES,
  WIRE_STYLES,
} from '../utils/wireShapes';

const text = (key, label) => ({ key, label, type: 'text' });
const area = (key, label) => ({ key, label, type: 'textarea' });
const link = (key, label) => ({ key, label, type: 'link' });
const image = (key, label) => ({ key, label, type: 'image' });
const select = (key, label, options) => ({
  key,
  label,
  type: 'select',
  options,
});

export const registry = {
  hero: {
    label: 'Hero',
    category: 'Content',
    icon: Sparkles,
    Component: Hero,
    defaults: {
      heading: 'Your headline here',
      subheading: 'Tell visitors what makes your store special.',
      buttonText: 'Shop now',
      buttonHref: '#/',
      image: '',
      align: 'left',
      height: 'md',
      wire: false,
      wireShape: 'terrain',
      wireStyle: 'both',
      wireColor: '#ffffff',
      wireSpeed: 50,
      wirePulse: true,
      wireInteractive: true,
      gridStyle: 'none',
      gridColor: '#ffffff',
    },
    fields: [
      text('heading', 'Heading'),
      area('subheading', 'Subheading'),
      text('buttonText', 'Button text'),
      link('buttonHref', 'Button link'),
      image('image', 'Background image'),
      select('align', 'Alignment', [
        ['left', 'Left'],
        ['center', 'Center'],
      ]),
      select('height', 'Height', [
        ['sm', 'Small'],
        ['md', 'Medium'],
        ['lg', 'Large'],
      ]),
      { key: 'wire', label: 'Wireframe animation', type: 'toggle' },
      select('wireShape', 'Wireframe shape', WIRE_SHAPES),
      select('wireStyle', 'Wireframe style', WIRE_STYLES),
      { key: 'wireColor', label: 'Wireframe color', type: 'color' },
      {
        key: 'wireSpeed',
        label: 'Wireframe speed',
        type: 'range',
        min: 0,
        max: 100,
      },
      { key: 'wirePulse', label: 'Traveling light pulses', type: 'toggle' },
      {
        key: 'wireInteractive',
        label: 'React to pointer (Preview and export)',
        type: 'toggle',
      },
      select('gridStyle', 'Background grid animation', GRID_STYLES),
      { key: 'gridColor', label: 'Grid color', type: 'color' },
    ],
  },
  productGrid: {
    label: 'Product grid',
    category: 'Store',
    icon: LayoutGrid,
    Component: ProductGrid,
    defaults: {
      heading: 'Our products',
      subheading: '',
      columns: 3,
      perPage: 8,
      paginationStyle: 'pages',
      showInCart: true,
      buttonText: 'Add to cart',
    },
    fields: [
      text('heading', 'Heading'),
      text('subheading', 'Subheading'),
      select('columns', 'Columns', [
        [2, '2'],
        [3, '3'],
        [4, '4'],
      ]),
      {
        key: 'perPage',
        label: 'Products per page (0 = all)',
        type: 'number',
        min: 0,
        max: 48,
      },
      select('paginationStyle', 'Pagination', [
        ['pages', 'Numbered pages'],
        ['loadmore', 'Load more button'],
        ['none', 'None (first page only)'],
      ]),
      { key: 'showInCart', label: 'Show "In cart" badge', type: 'toggle' },
      text('buttonText', 'Button text'),
    ],
  },
  featuredProduct: {
    label: 'Featured product',
    category: 'Store',
    icon: Star,
    Component: FeaturedProduct,
    defaults: { productId: '', label: 'Featured' },
    fields: [
      { key: 'productId', label: 'Product', type: 'product' },
      text('label', 'Label'),
    ],
  },
  imageText: {
    label: 'Image + text',
    category: 'Content',
    icon: ImageIcon,
    Component: ImageText,
    defaults: {
      heading: 'Tell your story',
      text: 'Share what your brand stands for and why customers love it.',
      image: '',
      imagePosition: 'left',
      buttonText: '',
      buttonHref: '#/',
    },
    fields: [
      text('heading', 'Heading'),
      area('text', 'Text'),
      image('image', 'Image'),
      select('imagePosition', 'Image position', [
        ['left', 'Left'],
        ['right', 'Right'],
      ]),
      text('buttonText', 'Button text'),
      link('buttonHref', 'Button link'),
    ],
  },
  features: {
    label: 'Features',
    category: 'Content',
    icon: BadgeCheck,
    Component: Features,
    defaults: {
      heading: '',
      imageShape: 'rounded',
      imageSize: 'md',
      items: [
        {
          image: '',
          title: 'Fast shipping',
          text: 'Orders leave in 24 hours.',
        },
        {
          image: '',
          title: 'Easy returns',
          text: '30 days, no questions asked.',
        },
        {
          image: '',
          title: 'Secure checkout',
          text: 'Your details stay private.',
        },
      ],
    },
    fields: [
      text('heading', 'Heading'),
      select('imageShape', 'Image shape', IMAGE_SHAPES),
      select('imageSize', 'Image size', IMAGE_SIZES),
      {
        key: 'items',
        label: 'Features',
        type: 'list',
        itemLabel: 'Feature',
        newItem: { image: '', title: 'New feature', text: '' },
        itemFields: [
          image('image', 'Image'),
          text('title', 'Title'),
          text('text', 'Text'),
        ],
      },
    ],
  },
  testimonials: {
    label: 'Testimonials',
    category: 'Content',
    icon: Quote,
    Component: Testimonials,
    defaults: {
      heading: 'What customers say',
      items: [
        { quote: 'Great quality and fast delivery.', author: 'Alex P.' },
        { quote: 'Exactly what I was looking for.', author: 'Sam R.' },
      ],
    },
    fields: [
      text('heading', 'Heading'),
      {
        key: 'items',
        label: 'Testimonials',
        type: 'list',
        itemLabel: 'Testimonial',
        newItem: { quote: 'Loved it!', author: 'Customer' },
        itemFields: [area('quote', 'Quote'), text('author', 'Author')],
      },
    ],
  },
  faq: {
    label: 'FAQ',
    category: 'Content',
    icon: CircleHelp,
    Component: Faq,
    defaults: {
      heading: 'Frequently asked questions',
      items: [
        {
          q: 'How long does shipping take?',
          a: 'Most orders arrive within 3 to 5 business days.',
        },
        {
          q: 'What is your return policy?',
          a: 'Return any item within 30 days for a full refund.',
        },
      ],
    },
    fields: [
      text('heading', 'Heading'),
      {
        key: 'items',
        label: 'Questions',
        type: 'list',
        itemLabel: 'Question',
        newItem: { q: 'New question?', a: 'Answer.' },
        itemFields: [text('q', 'Question'), area('a', 'Answer')],
      },
    ],
  },
  newsletter: {
    label: 'Newsletter',
    category: 'Content',
    icon: Mail,
    Component: Newsletter,
    defaults: {
      heading: 'Join our newsletter',
      text: 'Get news and offers in your inbox.',
      buttonText: 'Subscribe',
    },
    fields: [
      text('heading', 'Heading'),
      area('text', 'Text'),
      text('buttonText', 'Button text'),
    ],
  },
  banner: {
    label: 'Banner',
    category: 'Content',
    icon: Megaphone,
    Component: Banner,
    defaults: {
      text: 'Free shipping on orders over $50',
      buttonText: 'Shop now',
      buttonHref: '#/',
      tone: 'primary',
    },
    fields: [
      text('text', 'Text'),
      text('buttonText', 'Button text'),
      link('buttonHref', 'Button link'),
      select('tone', 'Style', [
        ['primary', 'Brand color'],
        ['dark', 'Dark'],
        ['light', 'Light'],
      ]),
    ],
  },
  richText: {
    label: 'Text',
    category: 'Content',
    icon: Type,
    Component: RichText,
    defaults: {
      heading: 'Section title',
      body: 'Write something here.',
      align: 'left',
    },
    fields: [
      text('heading', 'Heading'),
      area('body', 'Body'),
      select('align', 'Alignment', [
        ['left', 'Left'],
        ['center', 'Center'],
      ]),
    ],
  },
  spacer: {
    label: 'Spacer',
    category: 'Content',
    icon: MoveVertical,
    Component: Spacer,
    defaults: { height: 48 },
    fields: [
      { key: 'height', label: 'Height (px)', type: 'number', min: 8, max: 320 },
    ],
  },
  gallery: {
    label: 'Image gallery',
    category: 'Media',
    icon: Images,
    Component: Gallery,
    defaults: {
      heading: 'Gallery',
      columns: 3,
      items: [
        { image: '', caption: 'First image' },
        { image: '', caption: 'Second image' },
        { image: '', caption: 'Third image' },
      ],
    },
    fields: [
      text('heading', 'Heading'),
      select('columns', 'Columns', [
        [2, '2'],
        [3, '3'],
        [4, '4'],
      ]),
      {
        key: 'items',
        label: 'Images',
        type: 'list',
        itemLabel: 'Image',
        newItem: { image: '', caption: '' },
        itemFields: [image('image', 'Image'), text('caption', 'Caption')],
      },
    ],
  },
  video: {
    label: 'Video',
    category: 'Media',
    icon: VideoIcon,
    Component: Video,
    defaults: { heading: '', url: '' },
    fields: [text('heading', 'Heading'), text('url', 'YouTube or Vimeo link')],
  },
  logoCloud: {
    label: 'Logo cloud',
    category: 'Media',
    icon: Building2,
    Component: LogoCloud,
    defaults: {
      heading: 'As seen in',
      items: [
        { image: '', name: 'Brand one' },
        { image: '', name: 'Brand two' },
        { image: '', name: 'Brand three' },
        { image: '', name: 'Brand four' },
      ],
    },
    fields: [
      text('heading', 'Heading'),
      {
        key: 'items',
        label: 'Logos',
        type: 'list',
        itemLabel: 'Logo',
        newItem: { image: '', name: 'Brand' },
        itemFields: [image('image', 'Logo'), text('name', 'Name')],
      },
    ],
  },
  team: {
    label: 'Team',
    category: 'Media',
    icon: Users,
    Component: Team,
    defaults: {
      heading: 'Meet the team',
      imageShape: 'circle',
      imageSize: 'md',
      items: [
        { image: '', name: 'Alex Morgan', role: 'Founder' },
        { image: '', name: 'Sam Rivera', role: 'Design' },
        { image: '', name: 'Jordan Lee', role: 'Support' },
      ],
    },
    fields: [
      text('heading', 'Heading'),
      select('imageShape', 'Photo shape', IMAGE_SHAPES),
      select('imageSize', 'Photo size', IMAGE_SIZES),
      {
        key: 'items',
        label: 'Members',
        type: 'list',
        itemLabel: 'Member',
        newItem: { image: '', name: 'Name', role: 'Role' },
        itemFields: [
          image('image', 'Photo'),
          text('name', 'Name'),
          text('role', 'Role'),
        ],
      },
    ],
  },
  map: {
    label: 'Map',
    category: 'Media',
    icon: MapPin,
    Component: MapEmbed,
    defaults: {
      heading: 'Find us',
      query: '1600 Amphitheatre Parkway, Mountain View, CA',
      height: 'md',
    },
    fields: [
      text('heading', 'Heading'),
      text('query', 'Address or place'),
      select('height', 'Height', MAP_HEIGHTS),
    ],
  },
  cta: {
    label: 'Call to action',
    category: 'Content',
    icon: MousePointerClick,
    Component: CallToAction,
    defaults: {
      heading: 'Ready to get started?',
      text: 'Join thousands of happy customers today.',
      buttonText: 'Shop now',
      buttonHref: '#/',
      secondaryText: '',
      secondaryHref: '#/',
      tone: 'primary',
    },
    fields: [
      text('heading', 'Heading'),
      area('text', 'Text'),
      text('buttonText', 'Button text'),
      link('buttonHref', 'Button link'),
      text('secondaryText', 'Second button text'),
      link('secondaryHref', 'Second button link'),
      select('tone', 'Style', CTA_TONES),
    ],
  },
  stats: {
    label: 'Stats',
    category: 'Content',
    icon: BarChart3,
    Component: Stats,
    defaults: {
      heading: '',
      items: [
        { value: '10k+', label: 'Happy customers' },
        { value: '4.9', label: 'Average rating' },
        { value: '48h', label: 'Delivery' },
      ],
    },
    fields: [
      text('heading', 'Heading'),
      {
        key: 'items',
        label: 'Stats',
        type: 'list',
        itemLabel: 'Stat',
        newItem: { value: '100', label: 'Label' },
        itemFields: [text('value', 'Value'), text('label', 'Label')],
      },
    ],
  },
  pricing: {
    label: 'Pricing table',
    category: 'Content',
    icon: CreditCard,
    Component: Pricing,
    defaults: {
      heading: 'Pricing',
      subheading: 'Pick the plan that fits you.',
      items: [
        {
          name: 'Basic',
          price: '$9',
          period: '/mo',
          features: 'One user\nEmail support',
          buttonText: 'Choose Basic',
          buttonHref: '#/',
          highlight: false,
        },
        {
          name: 'Pro',
          price: '$29',
          period: '/mo',
          features: 'Five users\nPriority support\nAnalytics',
          buttonText: 'Choose Pro',
          buttonHref: '#/',
          highlight: true,
        },
      ],
    },
    fields: [
      text('heading', 'Heading'),
      text('subheading', 'Subheading'),
      {
        key: 'items',
        label: 'Plans',
        type: 'list',
        itemLabel: 'Plan',
        newItem: {
          name: 'Plan',
          price: '$0',
          period: '/mo',
          features: 'Feature',
          buttonText: 'Choose',
          buttonHref: '#/',
          highlight: false,
        },
        itemFields: [
          text('name', 'Name'),
          text('price', 'Price'),
          text('period', 'Period'),
          area('features', 'Features (one per line)'),
          text('buttonText', 'Button text'),
          link('buttonHref', 'Button link'),
          { key: 'highlight', label: 'Highlight this plan', type: 'toggle' },
        ],
      },
    ],
  },
  contact: {
    label: 'Contact form',
    category: 'Content',
    icon: MessageSquare,
    Component: ContactForm,
    defaults: {
      heading: 'Get in touch',
      text: 'Send us a message and we will reply soon.',
      buttonText: 'Send message',
    },
    fields: [
      text('heading', 'Heading'),
      area('text', 'Text'),
      text('buttonText', 'Button text'),
    ],
  },
  divider: {
    label: 'Divider',
    category: 'Content',
    icon: Minus,
    Component: Divider,
    defaults: { style: 'line' },
    fields: [select('style', 'Style', DIVIDER_STYLES)],
  },
  header: {
    label: 'Header',
    global: true,
    Component: Header,
    defaults: {},
    fields: [
      text('logoText', 'Logo text'),
      text('announcement', 'Announcement bar (optional)'),
      { key: 'showCart', label: 'Show cart icon', type: 'toggle' },
      { key: 'sticky', label: 'Stick to top when scrolling', type: 'toggle' },
      {
        key: 'links',
        label: 'Menu links',
        type: 'list',
        itemLabel: 'Link',
        newItem: { label: 'Link', href: '#/' },
        itemFields: [text('label', 'Label'), link('href', 'Link')],
      },
    ],
  },
  footer: {
    label: 'Footer',
    global: true,
    Component: Footer,
    defaults: {},
    fields: [
      area('about', 'About text'),
      text('copyright', 'Copyright line'),
      {
        key: 'links',
        label: 'Links',
        type: 'list',
        itemLabel: 'Link',
        newItem: { label: 'Link', href: '#/' },
        itemFields: [text('label', 'Label'), link('href', 'Link')],
      },
    ],
  },
};

export const paletteTypes = Object.keys(registry).filter(
  (t) => !registry[t].global,
);

export function createBlock(type, overrides = {}) {
  return {
    id: uid('b'),
    type,
    props: { ...structuredClone(registry[type].defaults), ...overrides },
  };
}
